### ISSUE TITLE
create crd fluentbit failed when making install

### ISSUE THREAD

**Issue by eilinge** [kubesphere/fluentbit-operator#13]
env:
controller-gen --version
Version: v0.2.4
kubernetes: GitVersion:"v1.16.0"
linuxOs: ubuntu18.04
go version: go1.14.1 linux/amd64

git clone https://github.com/kubesphere/fluentbit-operator.git
make install 

failed log:
customresourcedefinition.apiextensions.k8s.io/inputs.logging.kubesphere.io configured
customresourcedefinition.apiextensions.k8s.io/outputs.logging.kubesphere.io configured
The CustomResourceDefinition "fluentbits.logging.kubesphere.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
Makefile:30: recipe for target 'install' failed

**Comment by FeynmanZhou** [comment]
@huanggze Could you please help to look at this issue

**Comment by huanggze** [comment]
doc has been updated, please refer to README
