### ISSUE TITLE
Add shortNames for FluentBit FluentBitConfig CRDs

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/fluentbit-operator#40]
I expected to use short names to get the information about fluent-bit and fluent-bit-config CRs, but I found that I had to enter the full name. I think this is relatively inefficient, so I hope to add short names here. For example: 

- fluent-bit(fb)
- fluent-bit-config(fbc)

```sh
[root@ht-01 master]# kg -n kubesphere-logging-system fb
error: the server doesn't have a resource type "fb"
[root@ht-01 master]# kg -n kubesphere-logging-system fbc
error: the server doesn't have a resource type "fbc"
[root@ht-01 master]# kg -n kubesphere-logging-system fluentbit
NAME         AGE
fluent-bit   2d22h
[root@ht-01 master]# kg -n kubesphere-logging-system fluentbitconfig
NAME                AGE
fluent-bit-config   2d22h
[root@ht-01 master]#
```

If you agree, I can do this modification~

**Comment by benjaminhuo** [comment]
@daniel-hutao Adding short names as you described is a good idea.
Please go ahead with a PR

Ben

**Comment by daniel-hutao** [comment]
> @daniel-hutao Adding short names as you described is a good idea.
> Please go ahead with a PR
> 
> Ben

I'll do it soon
