### ISSUE TITLE
Helm Chart support

### ISSUE THREAD

**Issue by deveshk0** [kubesphere/fluentbit-operator#65]
is there any plan to support helm chart for deployment?

**Comment by benjaminhuo** [comment]
Yes, we're planning to provide helm chart support soon.

**Comment by benjaminhuo** [comment]
@wenchajun will help on creating a helm chart for Fluent Bit Operator.

**Comment by deveshk0** [comment]
Do you have any initial draft, i can also contribute Or I can push an initial  draft.

**Comment by benjaminhuo** [comment]
@deveshk0 We don't have an initial draft yet and of course we're happy to see the initial draft and PR from you.
https://github.com/kubesphere/fluentbit-operator/tree/master/manifests contains stuff you need to create a PR.
We're discussing with Fluent Community to contribute this project to Fluent, and you're welcome to join the slack and discuss this https://fluent-all.slack.com/archives/C02642TE9HR

**Comment by deveshk0** [comment]
Thanks @benjaminhuo  @wanjunlei, 

I couldn’t get time to work.

**Comment by benjaminhuo** [comment]
https://github.com/kubesphere/fluentbit-operator/tree/master/chart/fluentbit-operator Helm chart created

**Comment by FeynmanZhou** [comment]
> https://github.com/kubesphere/fluentbit-operator/tree/master/chart/fluentbit-operator

@wenchajun Could you add this chart to https://github.com/kubesphere/helm-charts/tree/master/src/main?

**Comment by wenchajun** [comment]
> > https://github.com/kubesphere/fluentbit-operator/tree/master/chart/fluentbit-operator
> 
> @wenchajun Could you add this chart to https://github.com/kubesphere/helm-charts/tree/master/src/main?

Ok, Sorry for the late reply. I will add it after modification and improvement
