### ISSUE TITLE
imagePullSecrets is not taking the values from values.yml for fluentbit daemonset

### ISSUE THREAD

**Issue by navneet066** [kubesphere/fluentbit-operator#92]
Right now imagePullSecrets are not defined in the CRD of the fluentbit https://github.com/kubesphere/fluentbit-operator/blob/master/chart/fluentbit-operator/crds/logging.kubesphere.io_fluentbit.yaml.

Are we planning to add that support?

It was not there for the operator also, I have modified the code and sent a PR for that.

Please let me know if I am missing anything

**Comment by wenchajun** [comment]
Thank you for your suggestion. I don't think it's necessary. Because fluentbit-operator is completely open-source. This( imagePullSecrets ) is the recommended approach to run containers based on images in private registries.

**Comment by deveshk0** [comment]
Since fluent bit operator is pushing images to docker hub and docker hub has a rate limit so it is a good idea to support that.
And JFYI all open source projects do support this

**Comment by benjaminhuo** [comment]
@navneet066 @deveshk0 We'll support this feature.
@wenchajun Would you help to add this feature?

**Comment by wenchajun** [comment]
Yes. He has modified the code and sent a PR for that(about fluentbit-operator).I have reviewed it.

**Comment by navneet066** [comment]
Yes. But that was only for the fluentbit-operator. For fluentbit daemonset, code changes are required.

**Comment by deveshk0** [comment]
Hi @wenchajun  I haved added a PR, Can you please have a look.

**Comment by navneet066** [comment]
It was done in this PR https://github.com/kubesphere/fluentbit-operator/pull/94
Thank you @deveshk0 

I will close this issue now
